In [1]:
import seaborn as sns
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import pandas as pd

In [2]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

# Binary classification

In [3]:
df = sns.load_dataset('iris')

## Delete a class to have a binary classification problem
df = df[df['species'] != 'setosa'] 

X = df.iloc[:,0:4].values
X = StandardScaler().fit_transform(X)
 
y = (df.iloc[:,4].values == 'versicolor').astype(int)
y[:5]

array([1, 1, 1, 1, 1])

In [4]:
model = Sequential([
    Dense(10,input_shape=(4,), activation='relu'), 
    Dense(6, activation='relu'),
    Dense(4, activation='relu'),
    Dense(1, activation='sigmoid') 
])
model.summary()
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
hist = model.fit(X, y, epochs=15, verbose=0)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 66        
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 28        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 5         
Total params: 149
Trainable params: 149
Non-trainable params: 0
_________________________________________________________________


# Multiclass classification

In [5]:
df = sns.load_dataset('iris')

X = df.iloc[:,0:4].values
X = StandardScaler().fit_transform(X)
 
y = df.iloc[:,4].values.reshape(-1,1)
y = OneHotEncoder(sparse=False).fit_transform(y)
y[:5,:]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [6]:
model = Sequential([
    Dense(10,input_shape=(4,), activation='relu'), 
    Dense(6, activation='relu'),
    Dense(4, activation='relu'),
    Dense(3, activation='softmax') 
])
model.summary()
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
hist = model.fit(X, y, epochs=15, verbose=0)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 10)                50        
_________________________________________________________________
dense_5 (Dense)              (None, 6)                 66        
_________________________________________________________________
dense_6 (Dense)              (None, 4)                 28        
_________________________________________________________________
dense_7 (Dense)              (None, 3)                 15        
Total params: 159
Trainable params: 159
Non-trainable params: 0
_________________________________________________________________


# Regression

In [7]:
df = sns.load_dataset('iris')

X = df.iloc[:,:3].values
X = StandardScaler().fit_transform(X)

y = df.iloc[:,3].values
y[:5]

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [8]:
model = Sequential([
    Dense(10,input_shape=(3,), activation='relu'), 
    Dense(6, activation='relu'),
    Dense(4, activation='relu'),
    Dense(1)  # Default activation: 'linear' 
])
model.summary()
model.compile(optimizer='adam', loss='mse', metrics=['mae'])
hist = model.fit(X, y, epochs=15, verbose=0)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 10)                40        
_________________________________________________________________
dense_9 (Dense)              (None, 6)                 66        
_________________________________________________________________
dense_10 (Dense)             (None, 4)                 28        
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 5         
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________
