In [1]:
import string
import numpy as np
from keras.preprocessing.text import Tokenizer
import itertools

2022-03-07 01:04:14.765570: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-07 01:04:14.765645: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
docs = ['I love love machine learning',
        'A machine can love',
        'I love love love']

tokens_docs = [doc.split(" ") for doc in docs]
tokens_docs

[['I', 'love', 'love', 'machine', 'learning'],
 ['A', 'machine', 'can', 'love'],
 ['I', 'love', 'love', 'love']]

In [3]:
# First, build an index of all tokens in the data.
all_tokens = itertools.chain.from_iterable(tokens_docs)
word_to_id = {token: idx for idx, token in enumerate(set(all_tokens))}
word_to_id

{'love': 0, 'machine': 1, 'can': 2, 'I': 3, 'A': 4, 'learning': 5}

In [4]:
nb_words = len(word_to_id)

res = []
for tokens_doc in tokens_docs:
    mat = np.zeros((len(tokens_doc), nb_words))
    for j, word in list(enumerate(tokens_doc)):
        index = word_to_id.get(word)
        mat[j, index] = 1.
    res.append(mat)

In [5]:
for i, x in enumerate(res):
    print(docs[i])
    print(x)
    print()


I love love machine learning
[[0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]

A machine can love
[[0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]

I love love love
[[0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]

